import * as THREE from 'three';
import {OrbitControls} from './vendor/OrbitControls.js';
const $=s=>document.querySelector(s),stage=$('#stage');let renderer;try{renderer=new THREE.WebGLRenderer({antialias:true});}catch(e){$('#error').hidden=false;throw e}renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;$('#canvas').append(renderer.domElement);
const scene=new THREE.Scene();scene.background=new THREE.Color('#e7edef');scene.fog=new THREE.Fog('#e7edef',65,140);const camera=new THREE.PerspectiveCamera(43,1,.1,200);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=1.5;controls.maxDistance=65;controls.maxPolarAngle=Math.PI*.49;controls.autoRotateSpeed=.6;scene.add(new THREE.HemisphereLight(0xe7f1ff,0xa9947c,2.4));const sun=new THREE.DirectionalLight(0xffebce,3.2);sun.position.set(-10,22,14);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-24,right:24,top:24,bottom:-24,near:1,far:65});sun.shadow.bias=-.0005;sun.shadow.normalBias=.035;scene.add(sun);const ground=new THREE.Mesh(new THREE.PlaneGeometry(250,250),new THREE.MeshStandardMaterial({color:0xe0e7ea,roughness:1}));ground.rotation.x=-Math.PI/2;ground.position.y=-.3;ground.receiveShadow=true;scene.add(ground);
const mat=(color,extra={})=>new THREE.MeshStandardMaterial({color,roughness:.65,...extra});const m={stone:mat(0xd9cdb8),wood:mat(0xbca17d),lightwood:mat(0xd4bfa0),dark:mat(0x343d46,{metalness:.35}),white:mat(0xf0eee5),black:mat(0x353332),brass:mat(0xaa8150,{metalness:.6}),blue:mat(0x618b91),glow:mat(0xffedcb,{emissive:0xffd99b,emissiveIntensity:1.4}),panel:mat(0xfaf7ee,{emissive:0xffedda,emissiveIntensity:.25}),glass:mat(0xbfd8db,{transparent:true,opacity:.13,roughness:.15,depthWrite:false}),slate:mat(0x5d6060)};let model=new THREE.Group(),roofGroup=new THREE.Group(),version=1,seed=1,layout={width:18,depth:23,side:1};scene.add(model);
function box(w,h,d,x,y,z,material,parent=model){const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),material);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o}
function cylinder(r,h,x,y,z,material,parent=model){const o=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,32),material);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o}
function line(a,b,r,material,parent=model){const av=new THREE.Vector3(...a),bv=new THREE.Vector3(...b),o=new THREE.Mesh(new THREE.CylinderGeometry(r,r,av.distanceTo(bv),8),material);o.position.copy(av).add(bv).multiplyScalar(.5);o.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),bv.sub(av).normalize());parent.add(o)}
function textLabel(text,x,y,z,size=.25,parent=model){const c=document.createElement('canvas');c.width=1024;c.height=128;const ctx=c.getContext('2d');ctx.fillStyle='#334c4b';ctx.font='500 42px sans-serif';ctx.textAlign='center';ctx.fillText(text,512,80);const texture=new THREE.CanvasTexture(c);texture.colorSpace=THREE.SRGBColorSpace;const mesh=new THREE.Mesh(new THREE.PlaneGeometry(size*8,size),new THREE.MeshBasicMaterial({map:texture,transparent:true,depthWrite:false,side:THREE.DoubleSide}));mesh.position.set(x,y,z);parent.add(mesh)}
function arch(z,r=2.9){const s=new THREE.Shape(),outer=r+.2,cy=1.55;s.moveTo(-outer,0);s.lineTo(-outer,cy);s.absarc(0,cy,outer,Math.PI,0,true);s.lineTo(outer,0);s.lineTo(r,0);s.lineTo(r,cy);s.absarc(0,cy,r,0,Math.PI,false);s.lineTo(-r,0);s.closePath();const rib=new THREE.Mesh(new THREE.ExtrudeGeometry(s,{depth:.26,bevelEnabled:true,bevelSegments:1,steps:1,bevelSize:.025,bevelThickness:.025,curveSegments:36}),m.dark);rib.position.z=z;rib.castShadow=true;rib.receiveShadow=true;model.add(rib);for(const side of [-1,1]){box(.12,1.45,.33,side*(r-.03),.76,z+.1,m.brass);box(.1,.75,.34,side*(r-.1),.55,z+.13,m.glow)}}
function niche(x,z,width=2.7){const g=new THREE.Group();g.position.set(x,0,z);model.add(g);const h=3.45,d=1.15;box(width,.16,d,0,.08,0,m.white,g);box(width,.18,d,0,h,0,m.white,g);box(.17,h,d,-width/2,h/2,0,m.white,g);box(.17,h,d,width/2,h/2,0,m.white,g);box(width,h,.13,0,h/2,-d/2,m.white,g);box(width-.26,.035,.1,0,h-.14,-.18,m.glow,g);line([-.75,2.67,.04],[.75,2.67,.04],.025,m.brass,g);line([-.62,2.67,.04],[-.62,3.27,.04],.009,m.brass,g);line([.62,2.67,.04],[.62,3.27,.04],.009,m.brass,g);cylinder(.42,.38,0,.29,0,m.black,g);const sculpture=new THREE.Mesh(new THREE.CylinderGeometry(.22,.48,1.05,32,1,true),m.blue);sculpture.position.set(0,1.95,.03);sculpture.castShadow=true;g.add(sculpture);box(.5,.27,.14,0,2.52,.03,m.blue,g);box(.12,.35,.17,.12,2.27,.08,m.white,g);box(width-.2,h-.2,.018,0,h/2,.59,m.glass,g);textLabel('藏 / COLLECTION',0,.67,.63,.12,g)}
function bench(x,z){box(2.5,.28,.72,x,.57,z,m.lightwood);for(const a of [-.9,.9])box(.12,.5,.5,x+a,.25,z,m.dark)}
function build(){scene.remove(model);model.traverse(o=>{if(o.geometry)o.geometry.dispose();if(o.material?.map){o.material.map.dispose();o.material.dispose()}});model=new THREE.Group();scene.add(model);roofGroup=new THREE.Group();model.add(roofGroup);const W=layout.width,D=layout.depth,H=Number($('#height').value)/10,N=Number($('#niches').value),A=Number($('#arches').value),back=-D/2,front=D/2,end=back+1.2;$('#dimensions').textContent=`${W} × ${D} m · 前厅高 ${H.toFixed(1)} m`;$('#arches-out').value=A+' 道';$('#niches-out').value=N+' 组';$('#height-out').value=H.toFixed(1)+' m';box(W,.25,D,0,-.125,0,m.stone);for(let x=-W/2+1.5;x<W/2;x+=1.5)box(.012,.003,D,x,.006,0,m.lightwood);for(let z=back+1.5;z<front;z+=1.5)box(W,.003,.012,0,.006,z,m.lightwood);
box(W,H,.28,0,H/2,back,m.wood);box(.25,H,D,-W/2,H/2,0,m.wood);box(.25,H,D,W/2,H/2,0,m.wood);for(let z=back;z<front;z+=1.35){box(.015,H,.018,-W/2+.135,H/2,z,m.brass);box(.015,H,.018,W/2-.135,H/2,z,m.brass)}box(W,.035,.1,0,H-.2,back+.22,m.glow);box(.1,.035,D,-W/2+.23,H-.2,0,m.glow);box(.1,.035,D,W/2-.23,H-.2,0,m.glow);
const wing=(W-6.6)/2;for(const sign of [-1,1]){box(wing,H,.28,sign*(3.3+wing/2),H/2,1,m.wood);for(let x=3.5;x<W/2;x+=1.2)box(.018,H,.02,sign*x,H/2,1.15,m.brass)}box(6.6,H-4.9,.28,0,4.9+(H-4.9)/2,1,m.wood);textLabel('光 序 / SPATIAL COLLECTION',0,5.27,1.17,.32);
box(5.85,.025,1-end,0,.025,(1+end)/2,m.slate);for(let i=0;i<A;i++){const step=(.4-end)/(A-1),z=.6-i*step;arch(z);if(i<A-1)box(1.4,.065,step-.25,0,4.35,z-step/2,m.panel,roofGroup)}for(const sign of [-1,1])for(let i=0;i<A-1;i++){const z=-.6-i*(.4-end)/(A-1);box(.65,.82,.9,sign*2.48,.41,z,m.dark);const screen=box(.7,.07,.62,sign*2.42,.9,z,m.black);screen.rotation.z=sign*.24;box(.05,.45,.7,sign*2.08,.42,z,m.glow)}
for(let i=0;i<N;i++){const sign=i%2===0?-1:1,row=Math.floor(i/2);niche(sign*(W/2-2.3),back+1.05+row*4.3)}
const s=layout.side;box(3.8,1.04,1.2,s*(W/2-3.1),.52,3.6,m.dark);box(4,.09,1.3,s*(W/2-3.1),1.085,3.6,m.stone);box(4.1,3.8,.16,s*(W/2-3.1),1.9,2.3,m.white);for(let i=0;i<22;i++)box(.035,4.65,.065,s*(W/2-3.1)-2+i*.19,2.325,2.04,m.lightwood);for(let y=.25;y<4.7;y+=.3)box(4.1,.026,.065,s*(W/2-3.1),y,2.04,m.lightwood);textLabel('合 境 / WELCOME',s*(W/2-3.1),1.64,2.405,.19);bench(-s*(W/2-3),4.8);bench(-s*(W/2-3),8);cylinder(.65,.42,-s*(W/2-3),.21,6.5,m.white);for(let i=0;i<3;i++){box(3.6,.08,.08,s*(W/2-3.1),H-1.55,3+i*.5,m.brass);box(.065,.065,1.9,s*(W/2-3.1)-1.2+i*1.2,H-1.49,3.5,m.glow)}for(const a of [-1.2,1.2])line([s*(W/2-3.1)+a,H-1.5,3.5],[s*(W/2-3.1)+a,H,3.5],.012,m.dark);
box(W,.16,front-1,0,H+.08,(front+1)/2,m.lightwood,roofGroup);for(let x=-W/2+2;x<W/2;x+=2.4)box(.02,.02,front-1,x,H-.01,(front+1)/2,m.brass,roofGroup);const warm=new THREE.PointLight(0xffdfa9,35,17,2);warm.position.set(0,H-1,6);model.add(warm);const fill=new THREE.PointLight(0xf0f5ff,22,14,2);fill.position.set(0,3.5,-5);model.add(fill);roofGroup.visible=$('#roof').checked}
function preset(name){controls.autoRotate=false;$('#rotate').setAttribute('aria-pressed','false');document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));const D=layout.depth;let pos,target;if(name==='lobby'){pos=[0,2.15,D/2-1.1];target=[0,2.4,-2]}else if(name==='corridor'){pos=[.15,1.75,.65];target=[0,2,-D/2]}else if(name==='niche'){pos=[-layout.width/2+2.2,1.8,-D/2+5];target=[-layout.width/2+2.2,1.8,-D/2+1]}else if(name==='plan'){pos=[0,38,.01];target=[0,0,0]}else{pos=[25,24,31];target=[0,1.2,-1]}camera.position.set(...pos);controls.target.set(...target);$('#roof').checked=!['plan','overview'].includes(name);roofGroup.visible=$('#roof').checked;controls.update()}
let timer;function notify(t){$('#toast').textContent=t;$('#toast').style.opacity=1;clearTimeout(timer);timer=setTimeout(()=>$('#toast').style.opacity=0,3000)}['arches','niches','height'].forEach(id=>$('#'+id).addEventListener('input',build));$('#roof').onchange=e=>roofGroup.visible=e.target.checked;$('#rotate').onclick=()=>{controls.autoRotate=!controls.autoRotate;$('#rotate').setAttribute('aria-pressed',String(controls.autoRotate))};$('#reset').onclick=()=>preset('overview');document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>preset(b.dataset.view));$('#shuffle').onclick=()=>{version++;seed++;layout={width:[17,19,18,20][seed%4],depth:[22,24,25,23][seed%4],side:seed%2?-1:1};$('#arches').value=3+Math.floor(Math.random()*4);$('#niches').value=2+Math.floor(Math.random()*3);$('#height').value=58+Math.floor(Math.random()*17);$('#version').textContent='/ '+String(version).padStart(2,'0');build();preset('overview');notify('已重组空间尺度、拱廊节奏与展龛数量')};function resize(){const w=stage.clientWidth,h=stage.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix()}new ResizeObserver(resize).observe(stage);renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();$('#error').hidden=false});build();preset('overview');resize();renderer.setAnimationLoop(()=>{controls.update();renderer.render(scene,camera)});
