"use client";
import { useEffect,useRef,useState } from "react";
import { motion,useReducedMotion } from "motion/react";
import { ArrowUpRight,Pause,Play } from "lucide-react";
import styles from "./clean-hero.module.css";
export default function CleanHero(){
 const video=useRef<HTMLVideoElement>(null),reduced=useReducedMotion();const [paused,setPaused]=useState(false);const [failed,setFailed]=useState(false);const [email,setEmail]=useState("");const [notice,setNotice]=useState("");
 useEffect(()=>{const el=video.current;if(!el)return;const media=window.matchMedia("(prefers-reduced-motion: reduce)");const stop=()=>{if(media.matches){el.pause();setPaused(true);}};stop();media.addEventListener("change",stop);return()=>media.removeEventListener("change",stop);},[]);
 const enter=(delay:number,y=20)=>({initial:{filter:reduced?"blur(0px)":"blur(10px)",opacity:reduced?1:0,y:reduced?0:y},animate:{filter:"blur(0px)",opacity:1,y:0},transition:{duration:.6,delay:reduced?0:delay}});
 return <section className={styles.hero} id="top" aria-labelledby="welcome-title"><video ref={video} className={styles.video} src="https://d8j0ntlcm91z4.cloudfront.net/user_38xzZboKViGWJOttwIXH07lWA1P/hf_20260317_100335_dc625816-c3c1-4b00-b93e-4cb301cf5ea5.mp4" autoPlay loop muted playsInline preload="auto" aria-hidden="true" onError={()=>setFailed(true)} onPlay={()=>setPaused(false)} onPause={()=>setPaused(true)}/><div className={styles.overlay}/>
 <nav className={styles.nav} aria-label="主导航"><a className={styles.logo} href="#top">After-Now</a><div className={`${styles.glass} ${styles.links}`}><a href="#top">首页</a><a href="#lab">工具与 Skill</a><a href="#works">作品</a><a href="#manifesto">关于我</a></div><a className={styles.start} href="#lab">开始创作 <ArrowUpRight size={16}/></a></nav>
 <div className={styles.content}><div className={`${styles.glass} ${styles.badge}`}>10K+ already subscribed</div><h1 id="welcome-title" aria-label="Focus in a Constantly Distracted World">{["Focus in a Constantly","Distracted World"].map((line,i)=><span className={styles.line} key={line} aria-hidden="true">{Array.from(line).map((char,j)=><motion.span key={j} {...enter(i*.35+j*.06,50)} transition={{duration:.35,delay:reduced?0:i*.35+j*.06}}>{char}</motion.span>)}</span>)}</h1><motion.p {...enter(.8)} className={styles.description}>Cut through the noise of notifications, endless feeds, and constant interruptions.<br/>Learn how to reclaim your attention and do meaningful work that truly matters.</motion.p><motion.div {...enter(1.1)} className={`${styles.glass} ${styles.action}`}><form className={styles.emailForm} onSubmit={e=>{e.preventDefault();setNotice("预览表单：订阅服务尚未连接，邮箱没有保存或发送。");}}><input type="email" aria-label="Email address" placeholder="Enter your email" value={email} onChange={e=>setEmail(e.target.value)} required/><button className={styles.start} type="submit">Join Waitlist <ArrowUpRight size={17}/></button></form></motion.div>{notice&&<p className={styles.notice} role="status">{notice}</p>}</div>
 <div className={styles.footer}><a href="#lab">工具与工作台 ↓</a><button className={styles.glass} aria-label={paused?"播放背景视频":"暂停背景视频"} onClick={async()=>{const el=video.current;if(!el)return;if(el.paused){try{await el.play();}catch{setPaused(true);}}else el.pause();}}>{paused?<Play size={14}/>:<Pause size={14}/>}</button></div>{failed&&<p className={styles.error} role="status">视频暂时无法加载，仍可进入工具。</p>}</section>;
}
